version: 2
jobs:
  test_compose:
    docker:
      - image: circleci/buildpack-deps
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Use example .env
          command: cp .example.env .env
      - run:
          name: Try booting the stack
          command: docker-compose up --detach
workflows:
  version: 2
  make_cake:
    jobs:
      - test_compose
